version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region cn-northwest-1 | docker login --username AWS --password-stdin 589233188167.dkr.ecr.cn-northwest-1.amazonaws.com.cn/cancer-backend-ui
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t cancer-api:latest .
      - docker tag cancer-backend-ui:latest 589233188167.dkr.ecr.cn-northwest-1.amazonaws.com.cn/cancer-backend-ui:latest     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 589233188167.dkr.ecr.cn-northwest-1.amazonaws.com.cn/cancer-backend-ui:latest
artifacts:
  files:
    - ./service/imagedefinitions.json
    - '**/*'
  name: BuildService
